# Homework 4
## Damian Franco
## CS-575

In [ ]:
# Importing the required modules
from numpy import *
import numpy as np
import matplotlib.pyplot as plt
import time
from prettytable import PrettyTable
import scipy
import scipy.linalg 
from pprint import pprint
%matplotlib inline
import math

In [ ]:
# Saves the current plot to desktop since working in Google Colab
from google.colab import files
#plt.savefig("my_plot.png", bbox_inches='tight', dpi=300)
#files.download("my_plot.png")

# Hilbert Matrix Linear System (#4)

In [ ]:
# Test out 3x3 hilbert matrix A
test_hilb = scipy.linalg.hilbert(3)
pprint(test_hilb)

array([[1.        , 0.5       , 0.33333333],
       [0.5       , 0.33333333, 0.25      ],
       [0.33333333, 0.25      , 0.2       ]])


In [ ]:
# Test out 3x1 vector b
print(test_hilb.sum(axis=1))

[1.83333333 1.08333333 0.78333333]


In [ ]:
# Digits of accuracy
dList_4 = []

In [ ]:
# Initialize all lists of precision testing
n_arr = [8, 9, 10, 11, 12]
estimatedList = []
condList = []
errList = []
resdList = []

# Parse through all hilbert matrices and save metrics
for curr_n in n_arr:
  # Initialize current system
  curr_hilb = scipy.linalg.hilbert(curr_n)
  curr_b = curr_hilb.sum(axis=1)
  curr_exact = np.ones(curr_n)
  # Calculate cond(Hilb)
  curr_cond = np.linalg.cond(curr_hilb)
  condList.append(curr_cond)
  # Evaluate current degree of accuracy
  currDeg = abs(np.log10(np.finfo(float).eps)) - np.log10(curr_cond)
  dList_4.append(currDeg)
  # Solve the system
  curr_x = scipy.linalg.solve(curr_hilb, curr_b)
  estimatedList.append(curr_x)
  # Calculate error
  curr_err = np.linalg.norm(np.subtract(curr_x, curr_exact), 2) / np.linalg.norm(curr_exact, 2)
  errList.append(curr_err)
  # Calculate residual
  curr_resd = np.linalg.norm(np.subtract(curr_b, np.matmul(curr_hilb, curr_x)), 2) / np.linalg.norm(curr_b, 2)
  resdList.append(curr_resd)

<ipython-input-83-cbe5c448d0b5>:21: LinAlgWarning: Ill-conditioned matrix (rcond=2.34967e-17): result may not be accurate.
  curr_x = scipy.linalg.solve(curr_hilb, curr_b)


In [ ]:
print(dList_4)

[5.470074245763609, 3.9605774293957907, 2.4487775368821083, 0.9356645850452612, -0.5898739793319052]


In [ ]:
print(condList)

[15257575538.060041, 493153755941.02344, 16024416987428.36, 522270131654983.3, 1.7515952300879806e+16]


In [ ]:
pprint(estimatedList)

[array([1.        , 1.        , 0.99999998, 1.00000009, 0.99999975,
       1.00000036, 0.99999975, 1.00000007]),
 array([1.        , 1.00000002, 0.99999968, 1.00000226, 0.99999173,
       1.00001685, 0.99998069, 1.00001164, 0.99999713]),
 array([1.        , 1.00000012, 0.99999754, 1.00002196, 0.99989669,
       1.00028075, 0.99954389, 1.00043705, 0.99977225, 1.00004976]),
 array([0.99999999, 1.0000007 , 0.99998226, 1.00019562, 0.9988477 ,
       1.00401296, 0.99133333, 1.01173207, 0.99031475, 1.00445673,
       0.99912388]),
 array([0.99999992, 1.00000954, 0.99970276, 1.00401853, 0.97073197,
       1.1278859 , 0.64538004, 1.63922505, 0.25335552, 1.54502986,
       0.77406075, 1.04060022])]


In [ ]:
# Print out solution of each matrix with 16 digits as shown
acc = 0
for lst in estimatedList:
  print('Solution Hilbert N =', n_arr[acc])
  print('[')
  for elm in lst:
    print(elm, ',')
  print(']\n')
  acc += 1

Solution Hilbert N = 8
[
0.9999999999751893 ,
1.0000000013243644 ,
0.9999999827152406 ,
1.0000000936054314 ,
0.9999997477168642 ,
1.0000003573922531 ,
0.9999997453681658 ,
1.0000000719206814 ,
]

Solution Hilbert N = 9
[
0.9999999997244754 ,
1.0000000188788813 ,
0.999999682016214 ,
1.0000022616936521 ,
0.9999917283646602 ,
1.000016848941065 ,
0.999980688579362 ,
1.0000116443966667 ,
0.9999971272205518 ,
]

Solution Hilbert N = 10
[
0.9999999986020816 ,
1.0000001176533098 ,
0.9999975447489388 ,
1.0000219556716656 ,
0.9998966936927095 ,
1.0002807451298925 ,
0.9995438858614614 ,
1.000437048199492 ,
0.999772254327487 ,
1.0000497568927875 ,
]

Solution Hilbert N = 11
[
0.9999999932145917 ,
1.0000006953133032 ,
0.999982263192807 ,
1.0001956191295815 ,
0.9988476956821298 ,
1.0040129585036024 ,
0.9913333298144259 ,
1.0117320723395629 ,
0.9903147531538478 ,
1.004456731273554 ,
0.9991238848830913 ,
]

Solution Hilbert N = 12
[
0.9999999238197383 ,
1.0000095414830872 ,
0.9997027601247802 ,
1.0040

In [ ]:
print(condList)

[15257575538.060041, 493153755941.02344, 16024416987428.36, 522270131654983.3, 1.7515952300879806e+16]


In [ ]:
# Create condition number table with sizes
myTable = PrettyTable(["N size", "Digits of Accuracy", "Digits Ceiling"])

ceilAcc = []
roundedAcc = []
for i in range(len(n_arr)):
  currD = dList_4[i] + 1
  roundedAcc.append(currD)
  currRound = ceil(currD)
  ceilAcc.append(currRound)

# Add rows
for i in range(len(n_arr)):
  myTable.add_row([n_arr[i], roundedAcc[i], ceilAcc[i]])

print(myTable)

+--------+--------------------+----------------+
| N size | Digits of Accuracy | Digits Ceiling |
+--------+--------------------+----------------+
|   8    | 6.470074245763609  |      7.0       |
|   9    | 4.960577429395791  |      5.0       |
|   10   | 3.4487775368821083 |      4.0       |
|   11   | 1.9356645850452612 |      2.0       |
|   12   | 0.4101260206680948 |      1.0       |
+--------+--------------------+----------------+


In [ ]:
# Create condition number table with sizes
myTable = PrettyTable(["N size", "Condition Number"])

# Add rows
for i in range(len(n_arr)):
  myTable.add_row([n_arr[i], condList[i]])

print(myTable)

+--------+------------------------+
| N size |    Condition Number    |
+--------+------------------------+
|   8    |   15257575538.060041   |
|   9    |   493153755941.02344   |
|   10   |   16024416987428.36    |
|   11   |   522270131654983.3    |
|   12   | 1.7515952300879806e+16 |
+--------+------------------------+


In [ ]:
# Create error table with sizes
myTable = PrettyTable(["N size", "Relative Error", "Relative Residual"])

# Add rows
for i in range(len(n_arr)):
  myTable.add_row([n_arr[i], errList[i], resdList[i]])

print(myTable)

+--------+------------------------+------------------------+
| N size |     Relative Error     |   Relative Residual    |
+--------+------------------------+------------------------+
|   8    | 1.838642341710091e-07  | 1.7351483300378842e-16 |
|   9    | 9.856184167582365e-06  | 8.299789597601006e-17  |
|   10   | 0.00023310366588429792 | 1.1786209713090174e-16 |
|   11   |  0.005597539673936445  | 2.364470360061518e-16  |
|   12   |  0.34866699576489485   | 1.3627830931511819e-16 |
+--------+------------------------+------------------------+


# Loss of Precision (#6)

In [ ]:
# Intialize x
x = 1.2e-8
nonsci_x = f"{x:.9f}"
print(nonsci_x)

0.000000012


In [ ]:
cos_sub = 1 - math.cos(x)
print(math.cos(x))

0.9999999999999999


In [ ]:
half_ang = 1 - 2*(math.sin(x/2))**2
print((1 - 2*(math.sin(x/2))**2))

0.9999999999999999


In [ ]:
# Calculate number of accurate digits -log10(ε/|x-y|)
d_cos = -np.log10((np.finfo(float).eps) / (abs(cos_sub)))
print(d_cos)

-0.3010299956639812


In [ ]:
# Calculate number of accurate digits -log10(ε/|x-y|)
d_half = -np.log10((np.finfo(float).eps) / (abs(half_ang)))
print(d_half)

15.653559774527022


In [ ]:
# Evaluate the given f(x) function
eval = (1 - math.cos(x)) / ((x)**2)
print(eval)

0.7709882115452477


In [ ]:
# Evaluate same f(x) function but with the half angle formula
eval_halfAngle = (1 - (1 - 2*(math.sin(x/2))**2)) / ((x)**2)
print(eval_halfAngle)

0.7709882115452477
