# Homework 7
## Damian Franco
## CS-575

This program implements two versions of the power iteration method to predicting the largest eigenvalue and its associated eigenvector. The first implementation is a naive version with no normalization techniques while the second implemenation utilizes normalization techniques to properly compute the eigenvectors associated with the largest eigenvalues predictions.

In [1]:
# Importing the required modules
from numpy import *
import numpy as np
import matplotlib.pyplot as plt
import time
from prettytable import PrettyTable
import scipy
import scipy.linalg 
from pprint import pprint
%matplotlib inline
import math

In [2]:
# Saves the current plot to desktop since working in Google Colab
from google.colab import files
#plt.savefig("my_plot.png", bbox_inches='tight', dpi=300)
#files.download("my_plot.png")

# Power Method

In [77]:
# Power iteration method, naive approach, not normailzed 
def powerIter(A, x, tol):
  lambdaList = []
  xList = []
  for i in range(tol):
    x = np.dot(A, x)
    eigenVal = abs(x).max()
    x = x / x.max()
    lambdaList.append(eigenVal)
    xList.append(x)
  return eigenVal, x, lambdaList, xList

In [112]:
# Normalized version of power iteration method
def powerIter_Normalized(A, x, tol):
    x_curr = x
    x_curr = x_curr / np.linalg.norm(x_curr) # Intial normalization
    eigenVal = 0
    eigenVec = np.zeros(tol)
    valList = []
    vecList = []

    for i in range(tol):
        y = np.matmul(A, x_curr)
        # Compute eigenvalue
        currEigenVal = np.dot(x_curr, y)
        eigenVal = currEigenVal
        valList.append(eigenVal)
        # Compute eigenvector
        currEigenVec = y / np.linalg.norm(y)
        eigenVec = currEigenVec
        vecList.append(eigenVec)
        # Update current eigenvector
        x_curr = eigenVec
        
    return eigenVal, eigenVec, valList, vecList


In [79]:
x_0 = np.array([0.5, 0.5, 0.5, 0.5])

In [80]:
A = np.array([[3, 1, 4, 1], [5, 9, 2, 6], [5, 3, 5, 8], [9, 7, 9, 3]])

In [81]:
lam, x_new, lamList, xList = powerIter(A, x_0, 20)

In [82]:
print(lam)
print(x_new)

19.549363635166152
[0.3164058  0.87789547 0.83960479 1.        ]


In [113]:
lam_Norm, x_Norm, lamList_Norm, xList_Norm = powerIter_Normalized(A, x_0, 20)

In [114]:
print(lam_Norm)
print(x_Norm)

19.549363635178807
[0.19714812 0.54700465 0.52314625 0.6230863 ]


In [83]:
lamList

[14.0,
 18.142857142857142,
 19.889763779527563,
 19.464568487727632,
 19.568210708293076,
 19.54449964661373,
 19.550416998286657,
 19.549084736099694,
 19.549422319904124,
 19.549347589288363,
 19.549366887769906,
 19.549362707883823,
 19.54936381418296,
 19.549363581289192,
 19.549363644933315,
 19.54936363202401,
 19.549363635701724,
 19.54936363499118,
 19.549363635204884,
 19.549363635166152]

In [84]:
xList

[array([0.32142857, 0.78571429, 0.75      , 1.        ]),
 array([0.31692913, 0.89173228, 0.86614173, 1.        ]),
 array([0.31710214, 0.87193191, 0.8341251 , 1.        ]),
 array([0.31645904, 0.87857833, 0.84111456, 1.        ]),
 array([0.31645273, 0.87753191, 0.83930019, 1.        ]),
 array([0.3164108 , 0.87792737, 0.83969202, 1.        ]),
 array([0.316409  , 0.87787306, 0.83958804, 1.        ]),
 array([0.31640623, 0.87789678, 0.83960986, 1.        ]),
 array([0.31640602, 0.87789407, 0.83960388, 1.        ]),
 array([0.31640584, 0.87789551, 0.83960509, 1.        ]),
 array([0.31640582, 0.87789538, 0.83960474, 1.        ]),
 array([0.3164058 , 0.87789547, 0.83960481, 1.        ]),
 array([0.3164058 , 0.87789547, 0.83960479, 1.        ]),
 array([0.3164058 , 0.87789547, 0.83960479, 1.        ]),
 array([0.3164058 , 0.87789547, 0.83960479, 1.        ]),
 array([0.3164058 , 0.87789547, 0.83960479, 1.        ]),
 array([0.3164058 , 0.87789547, 0.83960479, 1.        ]),
 array([0.3164

In [115]:
lamList_Norm

[20.0,
 19.485474860335195,
 19.54897963368161,
 19.55152526640655,
 19.549644377378673,
 19.549529748994665,
 19.549388120830027,
 19.549375237246416,
 19.549365606808475,
 19.549364450446447,
 19.54936378975692,
 19.549363692988635,
 19.54936364709169,
 19.549363639308527,
 19.549363636084703,
 19.549363635474343,
 19.549363635245776,
 19.549363635198716,
 19.54936363518238,
 19.549363635178807]

In [116]:
xList_Norm

[array([0.21272376, 0.51999141, 0.49635543, 0.66180724]),
 array([0.1948413 , 0.54821808, 0.53248555, 0.61477877]),
 array([0.19832121, 0.54532143, 0.52167639, 0.62541745]),
 array([0.19703713, 0.54702987, 0.52370378, 0.62263074]),
 array([0.19722024, 0.54689702, 0.52307018, 0.6232218 ]),
 array([0.19714337, 0.54700268, 0.52317971, 0.62306143]),
 array([0.19715262, 0.54699763, 0.52314245, 0.62309422]),
 array([0.19714796, 0.54700428, 0.52314828, 0.62308496]),
 array([0.19714841, 0.54700418, 0.52314607, 0.62308677]),
 array([0.19714812, 0.54700461, 0.52314637, 0.62308623]),
 array([0.19714814, 0.54700461, 0.52314624, 0.62308633]),
 array([0.19714812, 0.54700464, 0.52314625, 0.6230863 ]),
 array([0.19714812, 0.54700464, 0.52314625, 0.62308631]),
 array([0.19714812, 0.54700465, 0.52314625, 0.6230863 ]),
 array([0.19714812, 0.54700465, 0.52314625, 0.6230863 ]),
 array([0.19714812, 0.54700465, 0.52314625, 0.6230863 ]),
 array([0.19714812, 0.54700465, 0.52314625, 0.6230863 ]),
 array([0.1971

In [117]:
print(np.abs(lam - np.matmul(xList_Norm[1].T, np.matmul(A, xList_Norm[1]))))

0.00038400148454087457


In [118]:
print(np.abs(lam - np.matmul(xList_Norm[19].T, np.matmul(A, xList_Norm[19]))))

1.1468159755168017e-11


In [119]:
errorLam = []
for i in range(20):
  matMult = np.dot(xList_Norm[i].T, np.dot(A, xList_Norm[i]))
  errApprox = abs(lam - matMult)
  errorLam.append(errApprox)

In [120]:
errorLam

[0.06388877483095712,
 0.00038400148454087457,
 0.00216163124039781,
 0.00028074221252083476,
 0.0001661138285129482,
 2.4485663875140062e-05,
 1.1602080263628523e-05,
 1.9716423231841418e-06,
 8.152802948302451e-07,
 1.5459076863066912e-07,
 5.7822482801839215e-08,
 1.1925536114176793e-08,
 4.142375331639414e-09,
 9.185505689401907e-10,
 3.0819080620858585e-10,
 7.962341896927683e-11,
 3.256417357988539e-11,
 1.6228796084760688e-11,
 1.2654766123887384e-11,
 1.1468159755168017e-11]

In [121]:
errorFactor = [0.0]
for i in range(1, 20):
  currFact = errorLam[i-1] / errorLam[i]
  errorFactor.append(currFact)

In [122]:
errorFactor

[0.0,
 166.37637457924086,
 0.1776443073936172,
 7.69970151972564,
 1.690059250539467,
 6.784125983269792,
 2.110454618375673,
 5.88447515414029,
 2.4183613116697127,
 5.273796760646304,
 2.673540829446222,
 4.848627537432152,
 2.8789124981238876,
 4.509686751834275,
 2.9804606446258126,
 3.870605033018026,
 2.4451232816932142,
 2.0065674255691768,
 1.282425603593487,
 1.1034696406443618]

In [125]:
errorVec = []
pm = 1
for i in range(20):
  errVecCurr = np.linalg.norm(x_Norm - pm*xList_Norm[i])
  errorVec.append(errVecCurr)

In [126]:
errorVec

[0.056474546861129425,
 0.012768379455168599,
 0.0034357045390233805,
 0.0007289289507268106,
 0.00020231481158017772,
 4.20106060087738e-05,
 1.210384997107185e-05,
 2.4678981224583485e-06,
 7.391482731971982e-07,
 1.49269597325479e-07,
 4.627393432864414e-08,
 9.38520693200393e-09,
 2.9781336040662133e-09,
 6.160954825090357e-10,
 1.9698968857660358e-10,
 4.1929989472355166e-11,
 1.3238290062761579e-11,
 2.7605936331778352e-12,
 7.800910609569593e-13,
 0.0]

In [127]:
errorVecFactor = [0.0]
for i in range(1, 20):
  if errorVec[i] != 0:
    currFact = errorVec[i-1] / errorVec[i]
    errorVecFactor.append(currFact)
  else:
    errorVecFactor.append(0.0)

In [128]:
errorVecFactor

[0.0,
 4.423000354854642,
 3.7163787834905286,
 4.713359972323311,
 3.602944070350157,
 4.815803217357179,
 3.470846557845559,
 4.904517678799008,
 3.338840408546737,
 4.951767047280914,
 3.225781414334577,
 4.930518278808342,
 3.15137202682572,
 4.833883202548131,
 3.1275519391942894,
 4.698061961271913,
 3.1673266920099756,
 4.795450479802211,
 3.5388094689757614,
 0.0]

In [129]:
# Create error table with sizes
# Specify the Column Names while initializing the Table
myTable = PrettyTable(["Iteration", "Estimated EigenVal", "EigenVal Error", "EigenVal Error Factor", "EigenVec Error", "EigenVec Error Factor"])
iterNum = range(1,21)
# Add rows
for i in range(20):
  myTable.add_row([iterNum[i], lamList[i], errorLam[i], errorFactor[i], errorVec[i], errorVecFactor[i]])

print(myTable)

+-----------+--------------------+------------------------+-----------------------+------------------------+-----------------------+
| Iteration | Estimated EigenVal |     EigenVal Error     | EigenVal Error Factor |     EigenVec Error     | EigenVec Error Factor |
+-----------+--------------------+------------------------+-----------------------+------------------------+-----------------------+
|     1     |        14.0        |  0.06388877483095712   |          0.0          |  0.056474546861129425  |          0.0          |
|     2     | 18.142857142857142 | 0.00038400148454087457 |   166.37637457924086  |  0.012768379455168599  |   4.423000354854642   |
|     3     | 19.889763779527563 |  0.00216163124039781   |   0.1776443073936172  | 0.0034357045390233805  |   3.7163787834905286  |
|     4     | 19.464568487727632 | 0.00028074221252083476 |    7.69970151972564   | 0.0007289289507268106  |   4.713359972323311   |
|     5     | 19.568210708293076 | 0.0001661138285129482  |   1.69005